---
services:
  - name: docker
    image: docker:19.03.8-dind
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/persist/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /etc/docker/daemon.json:/etc/docker/daemon.json
     - /var/persist:/var/persist
     - /var/run:/var/run
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
    runtime:
      mkdir:
        - /var/lib/docker
        - /var/persist/docker
files:
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
