---
services:
  - name: docker
    image: docker:18.06.0-ce-dind
    capabilities:
     - all
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/docker/daemon.json:/etc/docker/daemon.json
     - /etc/resolv.cluster:/etc/resolv.conf
     - /lib/modules:/lib/modules
     - /var/persist:/var/persist
     - /var/run:/var/run
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
    runtime:
      mkdir:
        - /var/lib/docker
        - /var/persist/docker
files:
  - path: etc/docker/daemon.json
    contents: '{"dns":["172.17.0.1"],"data-root":"/var/persist/docker"}'
