services:
  - name: vault
    image: vault:1.3.1
    command: ["/bin/vault", "server", "-config", "/vault/config/server.hcl", "-config", "/vault/dynconfig"]
    capabilities:
      - CAP_SETUID
      - CAP_SETGID
      - CAP_IPC_LOCK
    binds:
      - /vault/config:/vault/config
      - /var/run/config/vault:/vault/dynconfig
      - /etc/resolv.conf:/etc/resolv.conf
files:
  - path: vault/config/server.hcl
    source: components/vault/server.hcl
    mode: "0644"
    optional: false
