services:
  - name: vault
    image: vault:1.3.1
    command: ["/bin/vault", "server", "-config", "/vault/config/server.hcl"]
    capabilities:
      - CAP_SETUID
      - CAP_SETGID
      - CAP_IPC_LOCK
    binds:
      - /vault/config:/vault/config
files:
  - path: vault/config/server.hcl
    source: components/vault/server.hcl
    mode: "0644"
    optional: false
