---
services:
  - name: nomad
    image: nomad:0.10.2
    capabilities:
      - CAP_CHOWN
      - CAP_SYS_ADMIN
    command: ["/bin/nomad", "agent", "-config", "/nomad/config/", "-config", "/nomad/dynconfig/"]
    binds:
      - /var/persist:/var/persist
      - /nomad/config:/nomad/config
      - /var/run/config/nomad:/nomad/dynconfig
      - /var/run:/var/run
    net: host
    runtime:
      mkdir: ["/nomad/config", "/var/run/config/nomad", "/var/persist/nomad"]
files:
  - path: nomad/config/base.hcl
    source: components/nomad/base.hcl
    mode: "0644"
    optional: false
  - path: nomad/config
    directory: true
    mode: "0755"
  - path: var/persist/nomad
    directory: true
    mode: "0755"
