kernel:
  image: linuxkit/kernel:4.19.90
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:1d8e0532ca588c5ad0d9ca6038349a70bb7ac626
  - linuxkit/runc:c1f0db27e71d948f3134b31ce76276f843849b0a
  - linuxkit/containerd:751de142273e1b5d2d247d2832d654ab92e907bc
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.7
  - name: ip
    image: linuxkit/ip:7b1cf3150bf5d9a0df7ef07572e2d81fe3c0c3d3
    binds:
      - /etc/ip:/etc/ip
    command: ["ip", "-b", "/etc/ip/eth0.conf"]
services:
  - name: getty
    image: linuxkit/getty:v0.7
    env:
     - INSECURE=true
  - name: dnsmasq
    image: dnsmasq
    net: host
    binds:
      - /var/log:/var/log
    capabilities:
      - all
files:
  - path: etc/ip/eth0.conf
    contents: |
      address add 192.168.10.1/24 dev eth0
      link set eth0 up
