---
services:
  - name: consul
    image: consul:1.6.1
    command: ["/bin/consul", "agent", "-config-dir", "/consul/config"]
    capabilities:
      - CAP_SETUID
      - CAP_SETGID
    binds:
      - /var/persist:/consul/data
      - /consul/config:/consul/config
    net: host
files:
  - path: consul/config/base.hcl
    source: components/consul/base.hcl
    mode: "0644"
    optional: false
